### ISSUE TITLE
Support for Cavium ThunderX / ThunderX2 cores

### ISSUE THREAD

**Issue by vielmetti** [ARM-software/CSAL#1]
I'm interested in using this library on Cavium ThunderX and ThunderX2. Any sort of roadmap for that? I didn't see those cores on the supported list.

**Comment by mikel-armbb** [comment]
The boards we list as supported are examples only.
The library supports the standard CoreSight trace architecture, which is independent of the cores it is attached to. In that respect any system is supported - you just need to write the necessary registration code for the library.
However, I would advise on checking that the Cavium  ThnuderX trace architecture is fully CoreSight compatible.

Regards

Mike
