### ISSUE TITLE
Cannot compile BAREMETAL target due to ERRDESC undefined

### ISSUE THREAD

**Issue by odin-** [ARM-software/CSAL#21]
If I move cs_get_device_struct below #define of ERRDESC it works fine. Using official GCC ARM crosscompiler.

Building using -DBAREMETAL -DLPAE -DDEBUG -DDIAG=1

> <command-line>: note: this is the location of the previous definition
> In file included from ../../csal/src/cs_access_cmnfns.h:50,
>                  from ../../csal/src/cs_access_cmnfns.c:19:
> ../../csal/src/cs_access_cmnfns.h: In function 'cs_get_device_struct':
> ../../csal/src/cs_access_cmnfns.h:285:19: error: 'ERRDESC' undeclared (first use in this function); did you mean 'CS_ERRDESC'?
>   285 |     assert(dev != ERRDESC);

**Comment by algrant-arm** [comment]
Apologies, a recent merge broke the DEBUG build. This will be fixed in the next hour or so and we will look at increasing the range of build options tested.

**Comment by odin-** [comment]
Great. Thanks for the quick feedback!

**Comment by algrant-arm** [comment]
Should be fixed by the latest change, which also fixes #7.

**Comment by odin-** [comment]
I can confirm this is fixed in 23182b51881312698d3b7a470ffbde9c54d041e1
