### ISSUE TITLE
Incorrect setting of the access type register

### ISSUE THREAD

**Issue by srki-pravi-frki** [ARM-software/CSAL#4]
The access type register is set to user mode and then immediately switched to kernel mode only.

https://github.com/ARM-software/CSAL/blob/0cfaa04e44c19047fde7df0c887f7db8c9900b8b/experimental/csprofile.c#L395-L396

**Comment by algrant-arm** [comment]
Fixed by c7e8890a288a9ebc256fe7d0fe7d825fb3e5b186.

The experimental tools are still experimental and it is likely there are other issues here.
